### ISSUE TITLE
How to adjust background?

### ISSUE THREAD

**Issue by vbauerster** [rakr/vim-one#59]
First of all thanks for this colorscheme. I mostly use the one with light background, but sometimes wish to adjust its background brightness. For example make bg a little darker or brighter depending on external illumination. How do I accomplish this? It is not clear from the readme page, should I use public `one#highlight` function? If yes, then which group?

**Comment by rakr** [comment]
Hi, sorry for the delay (off for a month), yes you can use the `one#highlight` function on the `Normal` group.
Give it a try and close the issue if that works.

**Comment by vbauerster** [comment]
Yes, it works. Thank you!

**Comment by super-cooper** [comment]
@vbauerster what command specifically did you use? I tried `one#highlight('Normal', '', '29353B', 'none')` and it was read as an invalid command. To be honest, it would be easier for me if I could just make it so that a custom background color was not defined, as I'd much prefer that vim use the same color as my terminal

**Comment by laggardkernel** [comment]
If you want change the color with the `one#highlight` API, you need to run the commands after `VimEnter` event. Otherwise, the `one#highlight` is not parsed as a function yet.

```vim
augroup vim-one-customization
  autocmd!
  one#highlight('Normal', '', '29353B', 'none')
augroup END
```

You can also have a try with [my fork of vim-one](https://github.com/laggardkernel/vim-one), which is capable of customize the color palette like this,

```vim
let g:one_dark_syntax_bg='#29353B'
```

I haven't opened a pr of this feature yet, because I'm waiting the decision from rakr for [my current pr](https://github.com/rakr/vim-one/pull/95).

I don't see a way for a color scheme using the same color of your terminal. Besides, for terminal, you mainly defines 16 ANSI colors and everything is done. While in vim, not only you need to define a color palette, but need to adjust the foreground and background colors for every part of the vim, all kinds of syntax highlights, diff, 3rd party plugins, etc. Color schemes for them are very different.

**Comment by super-cooper** [comment]
@laggardkernel hey, thanks for the quick reply! I'm gonna give your fork a shot :)
